service: api-gateway
provider:
  name: aws
  runtime: python3.6

package:
  exclude:
    - .vscode/**
    - env/**
    - __pycache__/**
    - package.json
    - environment.yml
  include:
    - common/**

functions:
  generalAuthorizer:
    handler: auth/authorizer.handler
    environment:
      SECRET_KEY: ${file(./environment.yml):secret_key}
      REFRESH_KEY: ${file(./environment.yml):refresh_key}

resources:
  Resources:
    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ApiGateway
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 60
        AuthorizerUri:
          Fn::Join:
            - ''
            - 
              - 'arn:aws:apigateway:'
              - Ref: "AWS::Region"
              - ':lambda:path/2015-03-31/functions/'
              - Fn::GetAtt: "GeneralAuthorizerLambdaFunction.Arn"
              - "/invocations"
        IdentitySource: method.request.header.Authorization
        IdentityValidationExpression: "Bearer .+"
        Name: api-authorizer
        RestApiId: { Ref: ApiGateway }
        Type: TOKEN
    ApiGatewayAuthorizerPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::GetAtt: GeneralAuthorizerLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal:
          Fn::Join: ["",["apigateway.", { Ref: "AWS::URLSuffix"}]]

  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: ApiGateway
      Export:
        Name: MyApiGateway-restApiId

    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGateway
          - RootResourceId
      Export:
        Name: MyApiGateway-rootResourceId

    apiGatewayAuthorizerId:
      Value:
        Ref: ApiGatewayAuthorizer
      Export:
        Name: MyApiAuthorizerId

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: ./env/bin/python3
    noDeploy: 
      - autopep8
      - pylint
      - pkg-resources
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
