service: dnd
provider:
  name: aws
  runtime: python3.6
  include:
    - token_validator/**
functions:
  auth:
    handler: token_handler.authorize
  test:
    handler: test.get
    events:
      - http:
          path: /
          method: get
          authorizer: auth
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    pythonBin: /home/kory/Documents/development/python/dnd/env/bin/python3
