service: dnd

provider:
  name: aws
  runtime: python3.6

package:
  exclude:
    - .vscode/**
    - env/**
    - __pycache__/**
    - package.json
    - environment.yml

functions:
  auth:
    handler: auth/handler.authorize
    environment:
      SECRET_KEY: ${file(./environment.yml):secret_key}
  users:
    handler: users/handler.get
    events:
      - http:
          path: /users
          method: get
          authorizer: auth

plugins:
- serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: ./env/bin/python3
