service: users

provider:
  name: aws
  runtime: python3.6
  apiGateway:
    restApiId:
      'Fn::ImportValue': MyApiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': MyApiGateway-rootResourceId

package:
  exclude:
    - .vscode/**
    - env/**
    - __pycache__/**
    - package.json
    - environment.yml

functions:
  login:
    handler: login.handler
    events:
      - http:
          path: /users/login
          method: post
  register:
    handler: register.handler
    events:
      - http:
          path: /users/register
          method: post