service: users

provider:
  name: aws
  runtime: python3.6
  apiGateway:
    restApiId:
      'Fn::ImportValue': MyApiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': MyApiGateway-rootResourceId

package:
  exclude:
    - .vscode/**
    - env/**
    - __pycache__/**
    - package.json
    - environment.yml

functions:
  getUsers:
    handler: handler.get
    events:
      - http:
          path: /users
          method: get
          authorizer:
            type: CUSTOM
            authorizerId:
              'Fn::ImportValue': MyApiAuthorizerId
